apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_USER: dXNlcjEyMw==
  MYSQL_PASSWORD: cG9rc2ll
  MYSQL_DATABASE: d29yZHByZXNzZGI=