apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_passwd: cGFzc3dvcmQ=
  user: d29yZHByZXNzLXVzZXI=
  user_passwd: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfgmap
data:
  db_host: mysql-svc
  db_name: Test_1234