apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: user-25
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    volumeMounts:
    - name: htmldir
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - name: liveness-port
      containerPort: 80
      hostPort: 80
    startupProbe:
      httpGet:
        path: /
        port: liveness-port
      failureThreshold: 3
      periodSeconds: 7
    livenessProbe:
      httpGet:
        path: /
        port: liveness-port
      failureThreshold: 3
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
  - name: busybox
    image: busybox
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: "admin"
    command: ["/bin/sh", "-c", "--"]
    args: ["while true; do echo $DUMMY_DATABASE_PASSWORD >> /html/index.html; sleep 10; done;"]
    volumeMounts:
    - name: htmldir
      mountPath: /html
  volumes:
  - name: htmldir
    emptyDir: {}
