apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":"2021-01-14T06:58:55Z","labels":{"key":"value","run":"nginx"},"name":"nginx","namespace":"user-22","resourceVersion":"2885722","selfLink":"/api/v1/namespaces/user-22/pods/nginx","uid":"43cbd56b-835c-4ed9-ba07-d8523d048776"},"spec":{"containers":[{"image":"nginx","imagePullPolicy":"Always","name":"nginx","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"default-token-hfjsz","readOnly":true}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"nodeName":"gke-esun-lecture-1-pool-4-4303c2db-sx11","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"default-token-hfjsz","secret":{"defaultMode":420,"secretName":"default-token-hfjsz"}}]},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2021-01-14T06:58:55Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2021-01-14T07:36:24Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2021-01-14T07:36:24Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2021-01-14T06:58:55Z","status":"True","type":"PodScheduled"}],"containerStatuses":[{"containerID":"docker://3656e5f1855dc6ea57f670f1fd35d9c0332b7a997ec8da47966ea179f66a0dbf","image":"nginx:latest","imageID":"docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa","lastState":{},"name":"nginx","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2021-01-14T07:36:23Z"}}}],"hostIP":"10.170.15.202","phase":"Running","podIP":"10.60.7.2","podIPs":[{"ip":"10.60.7.2"}],"qosClass":"BestEffort","startTime":"2021-01-14T06:58:55Z"}}
  creationTimestamp: "2021-01-14T06:58:55Z"
  labels:
    key: value
    run: nginx
  name: nginx
  namespace: user-22
  resourceVersion: "2891509"
  selfLink: /api/v1/namespaces/user-22/pods/nginx
  uid: 43cbd56b-835c-4ed9-ba07-d8523d048776
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    livenessProbe:
      httpGet:
        path: /
        port: liveness-port
        scheme: HTTP
      periodSeconds: 5
      timeoutSeconds: 1 

    readinessProbe:
      tcpSocket:
        port: 80
    env: 
    - name: DUMMY_DATABASE_PASSWORD
      value: "admin"
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hfjsz
      readOnly: true
  - image: busybox
    imagePullPolicy: Always
    name: busybox
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do echo DUMMY_DATABASE_PASSWORD >> /html/index.html && sleep 5; done;" ]
    volumeMounts:
    - name: shared-volume
      mountPath: /html
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-esun-lecture-1-pool-4-4303c2db-sx11
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hfjsz
    secret:
      defaultMode: 420
      secretName: default-token-hfjsz
  - name: shared-volume
    emptyDir: {}
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T06:58:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T07:36:24Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T07:36:24Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-14T06:58:55Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3656e5f1855dc6ea57f670f1fd35d9c0332b7a997ec8da47966ea179f66a0dbf
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:10b8cc432d56da8b61b070f4c7d2543a9ed17c2b23010b43af434fd40e2ca4aa
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-14T07:36:23Z"
  hostIP: 10.170.15.202
  phase: Running
  podIP: 10.60.7.2
  podIPs:
  - ip: 10.60.7.2
  qosClass: BestEffort
  startTime: "2021-01-14T06:58:55Z"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-01-14T07:33:30Z","labels":{"run":"nginx"},"name":"nginx-svc","namespace":"user-22","resourceVersion":"2885723","selfLink":"/api/v1/namespaces/user-22/services/nginx-svc","uid":"82b0da7d-d1ce-4dd0-b83f-4d2421cc5a2c"},"spec":{"clusterIP":"10.64.9.203","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"key":"value","run":"nginx"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-01-14T07:33:30Z"
  labels:
    run: nginx
  name: nginx-svc
  namespace: user-22
  resourceVersion: "2891510"
  selfLink: /api/v1/namespaces/user-22/services/nginx-svc
  uid: 82b0da7d-d1ce-4dd0-b83f-4d2421cc5a2c
spec:
  clusterIP: 10.64.9.203
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    key: value
    run: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

