apiVersion: v1
data:
  nginx.conf: "user  nginx;\r\nworker_processes  1;\r\n\r\nerror_log  /var/log/nginx/error.log
    warn;\r\npid        /var/run/nginx.pid;\r\n\r\nevents {\r\n    worker_connections
    \ 1024;\r\n}\r\n\r\nhttp {\r\n    log_format  main  '$remote_addr - $remote_user
    [$time_local] \"$request\" '\r\n                      '$status $body_bytes_sent
    \"$http_referer\" '\r\n                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';\r\n\r\n
    \   # Path to access.log & error.log\r\n    access_log /var/log/nginx/access.log
    \ main;\r\n    error_log /var/log/nginx/error.log  warn;\r\n\r\n    sendfile        on;\r\n
    \   keepalive_timeout  65;\r\n    gzip  on;\r\n\r\n    upstream backend {\r\n
    \       # must match the target service name\r\n        server wp-svc.user-1:80;\r\n
    \   }\r\n\r\n    server {\r\n        listen       80;\r\n        location / {\r\n
    \           # $http_host is the host name that users seen on the browser URL\r\n
    \           # and it equals to `HTTP_HOST` request header.\r\n            proxy_set_header
    Host $http_host;\r\n\r\n            # You have to change this according to your
    setup.\r\n            proxy_pass http://wp-svc.user-1;\r\n\r\n            # Modify
    `Location` of 301 or 302 HTTP response, so\r\n            # that the browser will
    follow the correct location.\r\n            proxy_redirect ~^http://[^/]*/(.*)
    http://$http_host/$1;\r\n        }\r\n    }\r\n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
  namespace: user-1
---
apiVersion: v1
data:
  fluent.conf: "<source>\r\n  type tail\r\n  path /logs/**/access.log\r\n  tag nginx.access\r\n
    \ format nginx\r\n</source>\r\n\r\n<source>\r\n  @type tail\r\n  format /^(?<time>\\d{4}/\\d{2}/\\d{2}
    \\d{2}:\\d{2}:\\d{2}) \\[(?<log_level>\\w+)\\] (?<pid>\\d+).(?<tid>\\d+): (?<message>.*)$/\r\n
    \ tag nginx.error\r\n  path /logs/**/error.log\r\n</source>\r\n\r\n<match nginx.access>\r\n
    \ @type stdout\r\n</match>\r\n\r\n<match nginx.error>\r\n  @type stdout\r\n</match>"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fluentd-config
  namespace: user-1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc
  name: nginx-svc
spec:
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deply
  name: nginx-deploy
  namespace: user-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - image: nginx:1.23.0
        name: nginx         
        livenessProbe:
          httpGet:
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 5 
          failureThreshold: 2
          periodSeconds: 30 
          timeoutSeconds: 3
        ports:
          - containerPort: 80
            name: "nginx-port"
        volumeMounts:
        - name: nginxconf
          mountPath: "/etc/nginx/"
          readOnly: true
        - name: log-storage
          mountPath: "/var/log/nginx/"
      - image: fluentd:v1.14.0-1.0
        name: fluentd 
        volumeMounts:
        - name: fluentdconf
          mountPath: "/fluentd/etc/"
          readOnly: true
        - name: log-storage
          mountPath: "/logs/"
      volumes:
        - name: fluentdconf
          configMap: 
            name: fluentd-config
            defaultMode: 0644
        - name: nginxconf
          configMap: 
            name: nginx-config
            defaultMode: 0400            
        - name: log-storage
          emptyDir: {}
