apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: mysql-svc
  namespace: user-25
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: mysql-port
  selector:
    run: mysql