apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: user-25
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/
    - name: logdir
      mountPath: /var/log/nginx
  - image: fluentd
    imagePullPolicy: Always
    name: fluentd
    resources: {}
    volumeMounts:
    - name: fluentd-config
      mountPath: /etc/fluentd/
    - name: logdir
      mountPath: /logs
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-conf
    - name: fluentd-config
      configMap:
        name: fluentd-conf
    - name: logdir
      emptyDir: {}