apiVersion: v1
kind: Service
metadata:
  labels:
    run: wordpress
  name: wordpress-svc
  namespace: user-25
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: wordpress-port
  selector:
    run: wordpress
  sessionAffinity: None
  type: ClusterIP
