apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    version: "1"
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: share-volume
    - name: busybox
      image: busybox:latest
      # container 內需要有個 process 持續執行才能存活
      # 因為是作為 demo share volume 之用
      command:
        - watch
        - echo 'Version 1' > /tmp/index.html
      volumeMounts:
        - mountPath: /tmp
          name: share-volume
  volumes:
    - name: share-volume
      emptyDir: {}