apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      type tail
      path /logs/**/access.log
      tag nginx.access
      format nginx
    </source>
    
    <source>
      @type tail
      format /^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)$/
      tag nginx.error
      path /logs/**/error.log
    </source>
    
    <match nginx.access>
      @type stdout
    </match>
    
    <match nginx.error>
      @type stdout
    </match>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    events {
        worker_connections  1024;
    }
    
    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        # Path to access.log & error.log
        access_log /var/log/nginx/access.log  main;
        error_log /var/log/nginx/error.log  warn;
    
        sendfile        on;
        keepalive_timeout  65;
        gzip  on;
    
        upstream backend {
            # must match the target service name
            server wordpress-service.user-11:80;
        }
    
        server {
            listen       80;
            location / {
                # $http_host is the host name that users seen on the browser URL
                # and it equals to `HTTP_HOST` request header.
                proxy_set_header Host $http_host;
    
                # You have to change this according to your setup.
                proxy_pass http://wordpress-service.user-11;
    
                # Modify `Location` of 301 or 302 HTTP response, so
                # that the browser will follow the correct location.
                proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fluentd-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: log-volume
          mountPath: "/var/log/nginx"
        - name: nginx-conf
          mountPath: "/etc/nginx"
      - name: fluentd
        image: fluentd
        volumeMounts:
        - name: log-volume
          mountPath: "/logs"
        - name: fluentd-conf
          mountPath: "/etc/fluentd"
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: nginx-conf
        configMap:
          name: nginx-config
      - name: fluentd-conf
        configMap:
          name: fluentd-config
  
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
