apiVersion: v1
kind: Pod
metadata:
  name: nignx-pod
  labels:
    version: "1"
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: log-volume
          mountPath: /var/logs
        - name: nginx-conf-volume
          mountPath: /etc/nginx
    - name: fluentd 
      image: fluentd:v1.9-1
      volumeMounts:
        - name: fluentd-conf-volume
          mountPath: /fluentd/etc
  volumes:
    - name: log-volume
      emptyDir: {}
    - name: share-volume
      emptyDir: {}
    - name: nginx-conf-volume
      configMap:
        name: nginx-conf
        items:
          - key: nginx-conf
            path: nginx.conf
        defaultMode: 0644
    - name: fluentd-conf-volume
      configMap:
        name: fluentd-conf
        items:
          - key: fluentd-conf
            path: fluentd.conf