apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.29
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 60
      tcpSocket:
        port: mysql-port
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 60
      tcpSocket:
        port: mysql-port
    ports:
    - containerPort: 3306
      name: mysql-port
    envFrom:
      - secretRef:
          name: mysql-secret