apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:6.0.0-apache
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 60
      httpGet:
        path: /
        port: 80
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 60
      httpGet:
        path: /
        port: 80
    env:
      - name: WORDPRESS_DB_HOST
        value: mysql
      - name: WORDPRESS_DB_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: WORDPRESS_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
      - name: WORDPRESS_DB_NAME
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_DATABASE