apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MWYyZDFlMmU2N2Rm
  MYSQL_DATABASE: ZGI=
  MYSQL_USER: dXNlcjE=
  MYSQL_PASSWORD: ZHNmc2Fnc2FzZHNhcQ==
