apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx
        readOnly: true
      - name: share-logs
        mountPath: /var/log/nginx
  - name: fluentd
    image: fluentd:latest
    volumeMounts:
      - name: fluentd-conf
        mountPath: /etc/fluent
        readOnly: true
      - name: share-logs 
        mountPath: /logs 
  volumes:
  - name: share-logs
    emptyDir: {}
  - name: nginx-conf
    configMap:
      name: nginx-conf
  - name: fluentd-conf
    configMap:
      name: fluentd-conf    