
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hands-on
  name: hands-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on
      environment: prod
      version: 1.0.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hands-on
        environment: prod
        version: 1.0.0
    spec:
      containers:
      - image: nginx:latest
        name: foobar
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: DB_HOST
          value: "192.168.0.1"
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          tcpSocket:
            port: 80
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
            httpHeaders:
            - name: kubelet-probe
              value: true
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
