apiVersion: v1
kind: Pod
metadata:
 name: frontend
 labels:
  name: frontend
spec:
  containers:
  - name: wordpress
    image: wordpress:4-php7.0
    ports:
    - name: wordpress-port
      containerPort: 80
    env:
    - name: WORDPRESS_DB_PASSWORD
      value: password
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
#透過連接80port檢測wordpress是否存活
    livenessProbe:
      tcpSocket:
        port: 80  
      initialDelaySeconds: 100
      failureThreshold: 3
      periodSeconds: 3
      timeoutSeconds: 5
#透過連接mysql port, 檢測是否可接收請求,無法連接mysql的話不能接收請求
    readinessProbe:
      tcpSocket:
        port: 3306
      initialDelaySeconds: 100
      failureThreshold: 3
      periodSeconds: 3
      timeoutSeconds: 5
  - name: mysql
    image: mysql:5.7.27
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
#透過連接port,檢測是否存活
    livenessProbe:
      tcpSocket:
        port: 3306
      initialDelaySeconds: 100
      failureThreshold: 3
      periodSeconds: 5
      timeoutSeconds: 5
  restartPolicy: Always
