apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: dXNlcg==
    password: cGFzc3dvcmQ=
    rootpassword: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycfgmap
data:
  database: test_database
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: rootpassword
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: mycfgmap
          key: database
    ports:
    - containerPort: 3306
      name: mysql-port
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
    targetPort: mysql-port
  selector:
    app: mysql
