apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 8888
    targetPort: 80
  type: LoadBalancer # choose the right type base on your kubernetes environment
