apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
data:
# If you're trying to create a configmap from a
# file, please be careful about the indent.
{{- if .Files.Get "config/fluentd.conf" }}
  fluentd-proxy-conf: |
{{ .Files.Get "config/fluentd.conf" | indent 4 }}
{{ else }}
{{ fail "invalid chart" }}
{{- end }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: {{ .Values.fluentd.image }}
          imagePullPolicy: {{ .Values.fluentd.pullPolicy }}
          env:
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
          volumeMounts:
            - mountPath: /fluentd/etc
              name: fluentd-conf
            - mountPath: /logs
              name: host-log-volume
      volumes:
        - name: fluentd-conf
          configMap:
            name: fluentd-conf
            defaultMode: 420
            items:
              - key: fluentd-proxy-conf
                path: fluent.conf
        - name: host-log-volume
          hostPath:
            # the path on host machine
            path: /var/log/wordpress-nginx/