apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_passwd: cGFzc3dvcmQ=
  # echo -n 'wordpress-user'|base64
  user: d29yZHByZXNzLXVzZXI=
  user_passwd: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfgmap
data:
  db_host: mysql-svc
  db_name: Test_1234

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None # headless service
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql-svc"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.wordpress.pullPolicy }}
          env:
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_passwd
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user_passwd
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-cfgmap
                  key: db_name
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi