apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-workshop
    run: nginx
  name: nginx
  namespace: user-27
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    env:
    - name: APP_NAME
      value: "nginx"
    - name: APP_VERSION
      value: "latest"
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 500Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 5
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-m2p72
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-m2p72
    secret:
      defaultMode: 420
      secretName: default-token-m2p72

