apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-node-port
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: nginx
  type: NodePort
status:
  loadBalancer: {}
