apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluentd:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: share-logs
          mountPath: /logs
        - name: fluent-conf
          mountPath: /fluentd/etc
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: share-logs
        hostPath:
          path: /logs
      - name: fluent-conf
        hostPath:
          path: /fluentd/etc
      - configMap:
        items:
          - key: fluent.conf
            path: fluent.conf
        name: fluent-conf
      name: fluent-conf

