apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:       
        - name: fluentd
          image: fluentd:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /logs
              name: share-logs
            - mountPath: /etc/fluentd
              name: fluent-conf
              readOnly: true
      volumes:
        - name: share-logs
          hostPath:
            path: /var/log/nginx/test-1
            type: DirectoryOrCreate
        - name: fluent-conf
          configMap:
            items:
              - key: fluent.conf
                path: fluent.conf
            name: fluent-conf
